### ISSUE TITLE
Add certificate for www subdomain

### ISSUE THREAD

**Issue by odegroot** [ssaunier/lockyourscreen#21]
https://lockyourscreen.com/ has a perfectly valid certificate.

https://www.lockyourscreen.com/ also exists, but it currently uses a generic github certificate, which is not valid for this domain.

Could you also add a certificate for the www subdomain?

**Comment by ssaunier** [comment]
Sadly, OVH seems to piggy back on the certificate from the original website (APEX domain) and does not provide a way to configure a redirect. I have a `CNAME` on `www` but I can't do much more through their console.
