### ISSUE TITLE
Please enable HTTPS

### ISSUE THREAD

**Issue by Daniel15** [ssaunier/lockyourscreen#9]
Not quite sure why HTTPS isn't working on your site, since GitHub Pages should have enabled it automatically a while back: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by vt0r** [comment]
HTTPS seems to be working fine when I just tested it, so I think this can be resolved by checking a box to enforce redirection of non-HTTPS connections like shown in this article:

https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by ssaunier** [comment]
Hi 👋 

I had to change the `A` record in the zone to point to the newest GitHub Pages IP addresses, then it took some time to actually generate the Let's Encrypt certificate against the proper domain name.

All good now, I ticked the box 😉 

![image](https://user-images.githubusercontent.com/414418/48258297-0ab6d300-e415-11e8-9f50-b9375b2f936e.png)

Happy to see this little page used!
